main.py
models/conditional_gans.py
models/discriminators.py
models/generators.py
models/trainer.py
utils/utils.py

* Save model for inference
* Have not tested that a forward pass can actually be done, but I think for now that's OK.
* Now automatically saves the CLI options to a txt file in the results directory
* Also simplified the initialisation of the GAN by inferring the number of channels

Basic SavedModel functionality

---

main.py
models/conditional_gans.py
models/trainer.py
settings.yaml
utils/utils.py

Just implemented inference for a standard GAN (image -> latent -> image) until we have a better idea of how we will structure the conditioning.

Inference for standard GAN

---

dataloaders/dataloaders.py
models/tabular_embedding.py
trainers/text_to_image_trainer.py
trainers/trainers.py
utils/data_helpers.py
utils/datasets.py

- Able to load the small CheXpert images along with the tabular data.
- It assumes that the data set is already downloaded since you need to ask for permission to get access to it.

Data loader for CheXpert 

---

main.py
models/conditional_gans.py
models/discriminators.py
models/generators.py
settings.yaml
trainers/text_to_image_trainer.py
utils/data_helpers.py

- bugfix: loss function sigmoid
- padding for convs
- custom weight initialisers
- create embedding which is mean of random samples drawn from 10 options
- converted dataset downloading to use a local copy of raw data if available, otherwise create it
- cropping preprocessing functionality for birds, cropping based on bounding boxes provided

Replicate stack gan

---

main.py
models/conditional_gans.py
models/discriminators.py
models/generators.py
trainers/text_to_image_trainer.py
utils/data_helpers.py
utils/datasets.py
utils/utils.py
visualise/sampler.py
visualise/utils.py
visualise/visualise.py

* We can now save images to file so that we can compare the generated stage 1 image against the real image. I also had to resolve a huge merge conflict so just check the discriminator and generator changes more carefully.
* Discriminator now uses inheritance
* Some minor linting

Visualisation for side0by-side comparison of generated and real images

---

main.py
models/conditional_gans.py
models/discriminators.py
models/generators.py
models/layers.py
trainers/base_trainer.py
trainers/text_to_image_trainer.py
visualise/visualise.py

* implement load framework
* add build methods to models and layers, and calls to call() functions
* made conditional augmentation custom layer
* implement side-by-side image viz

Saving and loading model

---

main.py
settings.yaml
trainers/base_trainer.py
trainers/image_trainer.py
trainers/text_to_image_trainer.py
utils/data_helpers.py
utils/datasets.py
utils/utils.py
visualise/sampler.py
visualise/visualise.py

- We now pass the validation loader in with the train loader so that after each epoch we can run validation. We log the log the validation losses.  
- I also added the text embedding as a parameter in the dataset object
Review this after PR #28 as this branch splits off from there.
Addresses issue #29

Validation now included during training

---

models/discriminators.py
models/generators.py
models/layers.py

* added stage 2 generator
* added stage 2 discriminator
* modified custom layers to accept activation function as a parameter

stage 2 model implementation

---

main.py
models/discriminators.py
models/generators.py
settings.yaml
trainers/base_trainer.py
trainers/text_to_image_trainer.py
utils/callbacks.py

* generic callback functionality
* learning rate decay implemented

callbacks with learning rate decay

---

main.py
models/discriminators.py
models/generators.py
models/layers.py
trainers/stage_1_trainer.py
trainers/stage_2_trainer.py
trainers/trainers.py

 Refactor trainer and introduce stage 2 trainer

---

main.py
shenanigan/models/stackgan/run.py
shenanigan/models/stackgan/stage1/trainer.py
shenanigan/models/stackgan/stage2/trainer.py
shenanigan/trainers/core.py

added checkpoint saving and loading on flag

WIP: model checkpointing

---

main.py
shenanigan/models/stackgan/run.py
shenanigan/models/stackgan/stage1/trainer.py
shenanigan/models/stackgan/stage2/trainer.py
shenanigan/trainers/core.py
shenanigan/utils/__init__.py
shenanigan/utils/logger.py
shenanigan/utils/model_helpers.py

* created checkpoint wrapper class
* removed continue-training parameter as was functionally the same as use-pretrained
* convert save/load model functionality to checkpoint saving/loading

Remove model saving

---

shenanigan/models/stackgan/settings.yaml
shenanigan/models/stackgan/stage1/model.py
shenanigan/models/stackgan/stage1/trainer.py
shenanigan/models/stackgan/stage2/model.py
shenanigan/models/stackgan/stage2/trainer.py

initially was to investigate using kl_loss from authors code (which is wrong) but it did not seem to change anything. Think it is useful to log kl_loss though so just adding that in

log kl_loss

---

shenanigan/utils/data_helpers.py
shenanigan/utils/datasets.py

* random left-right flipping
* random cropping

data augmentation

---

main.py
shenanigan/models/stackgan/evaluate.py
shenanigan/models/stackgan/stage1/trainer.py
shenanigan/models/stackgan/stage2/trainer.py
shenanigan/utils/data_helpers.py

We now only load the small or large images depending on if we are training stage 1 or 2. I tested with stage 1 but now stage 2.

Only load small or large images

---

shenanigan/models/stackgan/run.py
shenanigan/visualise/sampler.py
shenanigan/visualise/visualise.py

* bug fix: img_size not added to viz
* bug fix: run script reordered

fix visualisation

---

shenanigan/models/stackgan/stage1/model.py
shenanigan/models/stackgan/stage1/trainer.py
shenanigan/models/stackgan/stage2/model.py
shenanigan/models/stackgan/stage2/trainer.py
shenanigan/utils/logger.py
shenanigan/utils/model_helpers.py

* Ensure that we do not add a new metric row which has the same epoch number as the previous epoch (particularly useful for continuing training)
* Delete log file if we are not continuing from a previous checkpoint
* Track and save the components of the discriminator loss

Logging and metrics update

---

shenanigan/models/stackgan/run.py
shenanigan/trainers/core.py
shenanigan/utils/model_helpers.py

* separate save_every and save_best checkpointers
- these checkpointers save to separate directories which makes tracking easier
* NOTE:
- save_every is used as the restore checkpointer when --use-pretrained enabled because assume it will save more frequently
- save_best is used for visualisations and inference

Multiple checkpointers

---

shenanigan/callbacks/callbacks.py
shenanigan/layers/core.py
shenanigan/models/stackgan/layers.py
shenanigan/models/stackgan/run.py
shenanigan/models/stackgan/settings.yaml
shenanigan/models/stackgan/stage1/model.py
shenanigan/models/stackgan/stage2/layers.py
shenanigan/models/stackgan/stage2/model.py
shenanigan/utils/datasets.py
shenanigan/utils/model_helpers.py

* removed all use_bias=False
* fixed leaky relu bug is residual layer
* changed real loss to be 0.9 not ones_like
* default batch size from 64 -> 8
* brought back num_parallel_calls in map
* brought back prefetching in data loader
* fixed image dimension bug in flowers dataset
* save models using epoch number

Repo comparison

---

shenanigan/models/stackgan/stage1/model.py
shenanigan/models/stackgan/stage1/trainer.py
shenanigan/utils/utils.py

I've added F1, recall, and precision metrics for the discriminator in the hope that they will give us an indication of what is going wrong

Discriminator metrics

---

shenanigan/models/stackgan/stage1/model.py
shenanigan/models/stackgan/stage2/model.py
shenanigan/utils/__init__.py
shenanigan/utils/utils.py

Minor KL div function "fix" - just moved it into the `utils` since it is shared and not model dependent

Moved KL function into utils
